"""index_media_url

Revision ID: 5756632c9895
Revises: d34351f034a3
Create Date: 2025-11-26 15:47:23.690549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5756632c9895'
down_revision: Union[str, Sequence[str], None] = 'd34351f034a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_media_url'), 'messages', ['media_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_media_url'), table_name='messages')
    # ### end Alembic commands ###
