"""add_media_fields

Revision ID: 2249372b71e9
Revises: 30ae119233b5
Create Date: 2025-11-26 15:13:03.508070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2249372b71e9'
down_revision: Union[str, Sequence[str], None] = '30ae119233b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('meta_media_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_meta_media_id'), 'messages', ['meta_media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_meta_media_id'), table_name='messages')
    op.drop_column('messages', 'meta_media_id')
    op.drop_column('messages', 'caption')
    op.drop_column('messages', 'media_type')
    op.drop_column('messages', 'media_url')
    # ### end Alembic commands ###
