"""add_api_key_to_tenants

Revision ID: 30ae119233b5
Revises: 587f94905328
Create Date: 2025-11-26 01:40:16.641319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ae119233b5'
down_revision: Union[str, Sequence[str], None] = '587f94905328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('api_key', sa.String(), nullable=False))
    op.create_index(op.f('ix_tenants_api_key'), 'tenants', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_api_key'), table_name='tenants')
    op.drop_column('tenants', 'api_key')
    # ### end Alembic commands ###
