"""add_webhook_url_to_tenant

Revision ID: 90fd7a52df58
Revises: 34420429c83c
Create Date: 2025-11-29 23:10:24.339887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fd7a52df58'
down_revision: Union[str, Sequence[str], None] = '34420429c83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('webhook_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'webhook_url')
    # ### end Alembic commands ###
