"""add_reply_to_wamid

Revision ID: d34351f034a3
Revises: 2249372b71e9
Create Date: 2025-11-26 15:20:12.232212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34351f034a3'
down_revision: Union[str, Sequence[str], None] = '2249372b71e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_wamid', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_reply_to_wamid'), 'messages', ['reply_to_wamid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_reply_to_wamid'), table_name='messages')
    op.drop_column('messages', 'reply_to_wamid')
    # ### end Alembic commands ###
